branches:
  only:
   - master
language: python
python:
- '3.4'
before_script:
- pip3 install git+https://github.com/TheWreckingCrewUK/sqf.git
script:
- python3 tools/sqf_validator.py
- python3 tools/sqf_linter.py
- python3 tools/config_validator.py
notifications:
  email:
    on_success: never
    on_failure: never
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL