branches:
  only:
   - master
language: python
python:
- '3.4'
before_script:
- pip3 install sqflint
script:
- python3 tools/sqf_validator.py
- python3 tools/sqf_linter.py
- python3 tools/config_validator.py
notifications:
  email:
    on_success: never
    on_failure: never